version: "3"
services:
  discord-nice-embed-maker-for-my-yoy:
    image: thelovinator/discord-nice-embed-maker-for-my-yoy
    container_name: discord-nice-embed-maker-for-my-yoy
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "5000:5000"
    volumes:
      - uploads:/home/botuser/Uploads
    restart: unless-stopped
volumes:
  uploads:
