services:
  discord-embed:
    image: thelovinator/discord-nice-embed-maker-for-my-yoy
    container_name: discord-embed
    env_file:
      - .env
    environment:
      - SERVE_DOMAIN=${SERVE_DOMAIN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - UPLOAD_FOLDER=/Uploads
    ports:
      - "5000:5000"
    volumes:
      - uploads:/Uploads
    restart: unless-stopped
volumes:
  uploads:
