version: "3"
services:
  discord-embed:
    image: thelovinator/discord-nice-embed-maker-for-my-yoy
    container_name: discord-embed
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "5000:5000"
    volumes:
      - uploads:/Uploads
    restart: unless-stopped
volumes:
  uploads:
